### ISSUE TITLE
application.js not initially included

### ISSUE THREAD

**Issue by williamhancharek** [learn-co-curriculum/crud-with-validations-lab#10]
I might be missing something here, but I thought that application.js was supposed to be included as a default template file for every new rails application.  It did not seem to be included here - this confused me when I was asked to put some text into application.js and it was nowhere to be found?

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials to no longer require `application.js` and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
