### ISSUE TITLE
js issue

### ISSUE THREAD

**Issue by MiriamPeskowitz** [learn-co-curriculum/crud-with-validations-lab#12]
Hey, in this lab, the js-fix is on the solution files, but it hasn't been incorporated into the master file, and pipeline assets and js haven't yet been covered in the curriculum. It became an awesome experience, because one of the TC's, Matt, when through the whole pipeline creation process, but probably, the fixes should be moved into the master files that we students download. Thanks!

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials as Rails no longer requires jquery or JavaScript and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙

**Comment by MiriamPeskowitz** [comment]
Awesome, thanks! Glad to part of the journey. 

On Aug 27, 2018, at 4:11 PM, Maxwell Benton <notifications@github.com> wrote:

Thank you for spotting this issue and providing feedback.

We have updated the materials as Rails no longer requires jquery or JavaScript and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
