### ISSUE TITLE
JQuery UJS No Longer Required

### ISSUE THREAD

**Issue by ecssiah** [learn-co-curriculum/crud-with-validations-lab#14]
It appears as though Rails has incorporated everything that was done by JQuery UJS into Rails UJG, and, based on my own solution to this lab, it looks like students no longer have to add any additional functionality to their app in order to get the `link_to` delete functionality. By simply adding `method: delete` I was able to pass the delete specs.

https://github.com/rails/rails/issues/25208

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @ecssiah.

We have updated the materials to remove jquery and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
