### ISSUE TITLE
Recommend more encompassing tests and more explicit guidance

### ISSUE THREAD

**Issue by micahshute** [learn-co-curriculum/crud-with-validations-lab#15]
Hi, I just want to re-iterate and add some details to the previous issue posted. Tests are currently able to pass without meeting requirements - I specifically noticed that I could write nothing in my show.html.erb file at all and the tests would pass. This allows the lab to be passed without properly setting up the link_to with the method: :delete option, which requires more action than is provided in the lab. To make it work, I created an application.js file, and added the lines: 

//= require jquery
//= require jquery_ujs

Then, I added
<%= javascript_include_tag 'application' %> 
to the application.html.erb file (which is the only part which is touched on in the lab, but it doesn't say what to put in the javascript_include_tag method)

Lastly, I had to add 2 gems to my gemfile to get everything to work properly: 'jquery-rails' and 'rails-ujs'

I think this lab might need a little more guidance about how to get the :method => :delete option in the link_to working, as well as a touch up on tests to ensure that all requirements are met before it can be passed. Thanks!

**Comment by jenmyers** [comment]
This issues should now be resolved.
