### ISSUE TITLE
With_options method not explained

### ISSUE THREAD

**Issue by JoeQuattrone** [learn-co-curriculum/crud-with-validations-lab#19]
with_options if: :released? do |song|
    song.validates :release_year, presence: true
    song.validates :release_year, numericality: {
      less_than_or_equal_to: Date.today.year
    }

not talked about in the lessons. It was in section 5 of the rails validation docs. You only told us to focus on section 2

**Comment by jenmyers** [comment]
Thank you for your feedback! We're uncertain if this refers only the curriculum or if it refers to instructions given by someone else, but we are updating this lab to be clearer.
