### ISSUE TITLE
link_to 'Delete' doesn't work

### ISSUE THREAD

**Issue by lisamarie616** [learn-co-curriculum/crud-with-validations-lab#2]
Regarding this line of code in crud-with-validations-lab-v-000/app/views/songs/index.html.erb (line 27):

`<%= link_to 'Delete', song, method: :delete, data: { confirm: 'For real?' } %>`

I was having some trouble with this requirement "Allow deleting songs with a link, using link_to", so I pulled down the learn-co solution and found that it doesn't work either. The delete link created here goes to the show page rather than the destroy action.

I found this on SO:
http://stackoverflow.com/questions/18154916/rails-4-link-to-destroy-not-working-in-getting-started-tutorial
but even doing what's suggested in this post, I couldn't get it working.

**Comment by AnnJohn** [comment]
Thanks for @lisamarie616 for raising this. We'll look into it soon but in the mean time have you used the Ask a Question tool to get support? Thanks!

**Comment by lisamarie616** [comment]
Yes, the Learn expert who helped me said he was stumped on this one. I just
used a button instead and moved on. Thanks!
