### ISSUE TITLE
Need to include the jquery-rails gem in the Gemfile for this lab

### ISSUE THREAD

**Issue by merecka** [learn-co-curriculum/crud-with-validations-lab#23]
This lab explicitly states to use the `link_to` method in order to delete a Song from the database.  But in order to do this, JavaScript is required as `link_to` uses JavaScript functionality in Rails.  This lab's Gemfile does not have any JavaScript gem included and thus in order to get the `link_to` to work, it has to be added.  You need to do the following to get the link_to functionality to work properly:

1)  Add gem 'jquery-rails' to the Gemfile

2) Create an application.js file inside the apps\assets\javascripts folder and input the following lines:  

//= require jquery
//= require jquery_ujs

3)  Add the following line to the views\layouts\application.html.erb file

<%= javascript_include_tag "application" %>

**Comment by jenmyers** [comment]
As far as we can tell, this should be resolved by upgrading to the newest version of Rails. Thank you for contributing!
