### ISSUE TITLE
Delete not functional

### ISSUE THREAD

**Issue by fbohz** [learn-co-curriculum/crud-with-validations-lab#24]
Hello this lab passes without having a functional delete.

Here's how I solved it:

Gemfile:
gem 'jquery-rails'

app/assets/javascripts/application.js
//= require jquery
//= require jquery_ujs

Note: Sometimes rails generators have model.js you can rename to application.js

app/views/layouts/application.html.erb
 <%= javascript_include_tag "application" %>

**Comment by jenmyers** [comment]
As far as we can tell, this should be resolved by upgrading to the newest version of Rails. Thank you for contributing!
