### ISSUE TITLE
too much too fast here?

### ISSUE THREAD

**Issue by bmolina-nyc** [learn-co-curriculum/crud-with-validations-lab#5]
The Delete lab speaks about a method that works with javascript and rails 

From delete lesson
The data-confirm attribute and the data-method attribute rely on some JavaScript built into RailsI 

Example they share
<% @people.each do |person| %>

<div class="person">
  <span><%= person.name %></span>
  <%= link_to "Delete", person, method: :delete, data: { confirm: "Really?" } %>
</div>

<% end %>

In the writeup for this lesson - there is a bullet 5
Allow deleting songs with a link, using link_to. (HINT: You might need to add some functionality so that you can properly delete a song using just a link. Be sure to include your new assets in application.html.erb.)

I was able to make my delete logic work but not at all using the data mentioned above from the delete lesson. The writeup for this lab shows some docs that feel super confusing and I think this more elegant delete method (in the form_for helper) probably shouldn't get discussed/expected until we get to the rails and javascript portion.....it seems too advanced to figure out just based on the confusing docs shared.

**Comment by itzsaga** [comment]
Agreed that the links included in the readme ask way too much. A link to http://api.rubyonrails.org/classes/ActionView/Helpers/UrlHelper.html#method-i-link_to would be more helpful towards a solution like `<%= link_to 'Delete', song, method: :delete, data: { confirm: 'You sure?' } %>`

**Comment by marielfrank** [comment]
I think more clear instructions surrounding the delete method would be helpful. I just added a pull request to give clearer instructions:

> 1. Allow deleting songs with a link, using `link_to`. (HINT: You'll need to [add some functionality](https://github.com/rails/jquery-ujs) and the file `app/assets/javascripts/application.js` for the jQuery `require` lines so that you can properly delete a song using just a link. Be sure to [include your new assets](http://apidock.com/rails/v4.2.1/ActionView/Helpers/AssetTagHelper/javascript_include_tag) using the tag `<%= javascript_include_tag 'application' %>` in `application.html.erb`.)

**Comment by maxwellbenton** [comment]
Thank you all for spotting this and providing feedback.

We have updated the materials and believe this issue has been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
