### ISSUE TITLE
Lab passed without fulfilling all of the requirements

### ISSUE THREAD

**Issue by jmb521** [learn-co-curriculum/crud-with-validations-lab#6]
There doesn't seem to be enough tests to ensure that all of the requirements are fulfilled. I was able to get the test to pass without using strong params or error lists. Also, the delete portion that requires javascript seems ambiguous.

**Comment by jenmyers** [comment]
Hi there,

Thank you for your feedback! We'll take this information into consideration in upcoming releases of this curriculum.

As always, thanks for contributing! 💙
