### ISSUE TITLE
Master branch of lab is missing jquery needed to implement delete route

### ISSUE THREAD

**Issue by christinalcole** [learn-co-curriculum/crud-with-validations-lab#7]
The master and solution branches for this lab differ regarding jquery inclusion. The solution branch has a commit from March 2016, "Include jquery_ujs so deletion works."  Files associated with this change are necessary to implement the delete action written as one of the lab's requirements.  Since a student forks the master branch when opening the lab, attempts to actually 'see' the delete action work in-browser/in console will fail (because the jquery gem and javascript loading via layout.html.erb aren't implemented in the master branch).  Lab tests will pass--it's just browser action that's affected.  Can the layout.html.erb, application.js, and Gemfile (all master branch) be modified as needed to match the solution branch?

**Comment by itzsaga** [comment]
@christinalcole the jquery isn't needed for delete to work. The readme needs to be updated. This is mentioned in #5

**Comment by christinalcole** [comment]
Good catch on the `readme`--totally overlooked that hint while working the lab!  Not sure how you can get the delete to work in-browser without adding the jquery_ujs functionality, though: the specs will pass either way.  Perhaps a better recommendation could be to tweak the `readme` hint to something along the lines of 'You will need to add some functionality in order to test...in-browser.' ?

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the master and solution branches, removed any references to jquery and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
